export const list = (ctx) => {};
export const write = (ctx) => {};
export const read = (ctx) => {};
export const remove = (ctx) => {};
export const replace = (ctx) => {};
export const update = (ctx) => {};
// exports.list = (ctx) => {};
// exports.write = (ctx) => {};
// exports.read = (ctx) => {};
// exports.remove = (ctx) => {};
// exports.replace = (ctx) => {};
// exports.update = (ctx) => {};
